### ISSUE TITLE
[S1 - PBI 3] Membuat Register

### ISSUE THREAD

**Issue by rvnger** [rvnger/SI4304-TIM-B#2]
saya sebagai project manager membuat laman untuk registrasi pengguna website

**Comment by rvnger** [comment]
<img width="375" alt="SiJuara" src="https://user-images.githubusercontent.com/87320209/159214475-614c6d95-f04d-4861-bafd-2f957e43fe8f.png">

Menambahkan contoh mockup register

**Comment by shazkiaseptiaweni** [comment]
Kerja;in sendiri

**Comment by rvnger** [comment]
tolong buatkan button yang mengarahkan ke dashboard

**Comment by yadinugrahaa** [comment]
Semangat! banyak doa aja
